* PROGRAMA CONVERSÃO DE CELSIUS PARA FAHRENHEIT

* PEGA O VALOR INSERIDO PELO USUARIO
LPARAMETERS lnCelsius


* DECLARAÇÃO DO RETORNO
LOCAL lnFahrenheit as Number

* NESSE CASO PEGAREI O  VALOR POR MEIO DO INPUTBOX (FUNÇÃO DE INTERAÇÃO COM O USER)
* NÃO ESQUECER QUE O INPUBOX RETORNA COMO STRING, POR ISSO A UTILIZAÇÃO DA FUNÇÃO VAL() PARA CONVERTER EM NUMBER
lnCelsius = VAL(INPUTBOX('Digite a temperatura em Celsius:', 'Conversão de Celsius para Fahrenheit'))

IF TYPE('lnCelsius') <> 'N'
	RETURN (MESSAGEBOX('DIGITE UM NÚMERO!!!', 0+16, 'ERROR'))
ENDIF

* CALCULO DA CONVERSÃO
lnFahrenheit = lnCelsius * 9 / 5 + 32

	
* RETORNO COM UMA CASA DECIMAL
? 'Temperatura em Fahrenheit'
RETURN (ROUND(lnFahrenheit, 1))

